// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBRPC.proto

package com.dust.epidemic.net.rpc;

public final class PBRPC {
  private PBRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.dust.epidemic.net.rpc.PBRPC.procId);
    registry.add(com.dust.epidemic.net.rpc.PBRPC.dataIn);
    registry.add(com.dust.epidemic.net.rpc.PBRPC.dataOut);
    registry.add(com.dust.epidemic.net.rpc.PBRPC.interfaceId);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int PROC_ID_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Integer> procId = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int DATA_IN_FIELD_NUMBER = 50004;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> dataIn = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int DATA_OUT_FIELD_NUMBER = 50003;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> dataOut = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int INTERFACE_ID_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Integer> interfaceId = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013PBRPC.proto\032 google/protobuf/descripto" +
      "r.proto:1\n\007proc_id\022\036.google.protobuf.Met" +
      "hodOptions\030\321\206\003 \001(\007:1\n\007data_in\022\036.google.p" +
      "rotobuf.MethodOptions\030\324\206\003 \001(\010:2\n\010data_ou" +
      "t\022\036.google.protobuf.MethodOptions\030\323\206\003 \001(" +
      "\010:7\n\014interface_id\022\037.google.protobuf.Serv" +
      "iceOptions\030\322\206\003 \001(\007B\033\n\031com.dust.epidemic." +
      "net.rpc"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    procId.internalInit(descriptor.getExtensions().get(0));
    dataIn.internalInit(descriptor.getExtensions().get(1));
    dataOut.internalInit(descriptor.getExtensions().get(2));
    interfaceId.internalInit(descriptor.getExtensions().get(3));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
