// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface FindRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string targetId = 1;</code>
   * @return The targetId.
   */
  String getTargetId();
  /**
   * <code>string targetId = 1;</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();

  /**
   * <code>.NodeInfo nodeInfo = 2;</code>
   * @return Whether the nodeInfo field is set.
   */
  boolean hasNodeInfo();
  /**
   * <code>.NodeInfo nodeInfo = 2;</code>
   * @return The nodeInfo.
   */
  NodeInfo getNodeInfo();
  /**
   * <code>.NodeInfo nodeInfo = 2;</code>
   */
  NodeInfoOrBuilder getNodeInfoOrBuilder();
}
