// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface NodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *发出信息的节点id
   * </pre>
   *
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  String getNodeId();
  /**
   * <pre>
   *发出信息的节点id
   * </pre>
   *
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <pre>
   *发出信息的节点对外端口
   * </pre>
   *
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();
}
