// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  String getNodeId();
  /**
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>int32 timestamp = 2;</code>
   * @return The timestamp.
   */
  int getTimestamp();

  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  int getPort();
}
