// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 timestamp = 1;</code>
   * @return The timestamp.
   */
  int getTimestamp();
}
