// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface PingPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  String getNodeId();
  /**
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>int32 timestamp = 2;</code>
   * @return The timestamp.
   */
  int getTimestamp();
}
