// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface StoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileId = 1;</code>
   * @return The fileId.
   */
  String getFileId();
  /**
   * <code>string fileId = 1;</code>
   * @return The bytes for fileId.
   */
  com.google.protobuf.ByteString
      getFileIdBytes();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>.NodeInfo nodeInfo = 3;</code>
   * @return Whether the nodeInfo field is set.
   */
  boolean hasNodeInfo();
  /**
   * <code>.NodeInfo nodeInfo = 3;</code>
   * @return The nodeInfo.
   */
  NodeInfo getNodeInfo();
  /**
   * <code>.NodeInfo nodeInfo = 3;</code>
   */
  NodeInfoOrBuilder getNodeInfoOrBuilder();
}
