// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

public interface StoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string errmsg = 2;</code>
   * @return The errmsg.
   */
  String getErrmsg();
  /**
   * <code>string errmsg = 2;</code>
   * @return The bytes for errmsg.
   */
  com.google.protobuf.ByteString
      getErrmsgBytes();
}
