// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dust.grpc.kademlia;

/**
 * <pre>
 *存储请求，携带有一个sha1编码的key和数据对象。其中key还是该对象的checksum
 * </pre>
 *
 * Protobuf type {@code StoreRequest}
 */
public final class StoreRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StoreRequest)
    StoreRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StoreRequest.newBuilder() to construct.
  private StoreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StoreRequest() {
    fileId_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new StoreRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StoreRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            fileId_ = s;
            break;
          }
          case 18: {

            data_ = input.readBytes();
            break;
          }
          case 26: {
            NodeInfo.Builder subBuilder = null;
            if (nodeInfo_ != null) {
              subBuilder = nodeInfo_.toBuilder();
            }
            nodeInfo_ = input.readMessage(NodeInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nodeInfo_);
              nodeInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return KademliaServiceProto.internal_static_StoreRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return KademliaServiceProto.internal_static_StoreRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StoreRequest.class, Builder.class);
  }

  public static final int FILEID_FIELD_NUMBER = 1;
  private volatile Object fileId_;
  /**
   * <code>string fileId = 1;</code>
   * @return The fileId.
   */
  @Override
  public String getFileId() {
    Object ref = fileId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileId_ = s;
      return s;
    }
  }
  /**
   * <code>string fileId = 1;</code>
   * @return The bytes for fileId.
   */
  @Override
  public com.google.protobuf.ByteString
      getFileIdBytes() {
    Object ref = fileId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  @Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int NODEINFO_FIELD_NUMBER = 3;
  private NodeInfo nodeInfo_;
  /**
   * <code>.NodeInfo nodeInfo = 3;</code>
   * @return Whether the nodeInfo field is set.
   */
  @Override
  public boolean hasNodeInfo() {
    return nodeInfo_ != null;
  }
  /**
   * <code>.NodeInfo nodeInfo = 3;</code>
   * @return The nodeInfo.
   */
  @Override
  public NodeInfo getNodeInfo() {
    return nodeInfo_ == null ? NodeInfo.getDefaultInstance() : nodeInfo_;
  }
  /**
   * <code>.NodeInfo nodeInfo = 3;</code>
   */
  @Override
  public NodeInfoOrBuilder getNodeInfoOrBuilder() {
    return getNodeInfo();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileId_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(2, data_);
    }
    if (nodeInfo_ != null) {
      output.writeMessage(3, getNodeInfo());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileId_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, data_);
    }
    if (nodeInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNodeInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StoreRequest)) {
      return super.equals(obj);
    }
    StoreRequest other = (StoreRequest) obj;

    if (!getFileId()
        .equals(other.getFileId())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (hasNodeInfo() != other.hasNodeInfo()) return false;
    if (hasNodeInfo()) {
      if (!getNodeInfo()
          .equals(other.getNodeInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILEID_FIELD_NUMBER;
    hash = (53 * hash) + getFileId().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    if (hasNodeInfo()) {
      hash = (37 * hash) + NODEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getNodeInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StoreRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StoreRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StoreRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StoreRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StoreRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StoreRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StoreRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StoreRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StoreRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StoreRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StoreRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StoreRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StoreRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *存储请求，携带有一个sha1编码的key和数据对象。其中key还是该对象的checksum
   * </pre>
   *
   * Protobuf type {@code StoreRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StoreRequest)
      StoreRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KademliaServiceProto.internal_static_StoreRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KademliaServiceProto.internal_static_StoreRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StoreRequest.class, Builder.class);
    }

    // Construct using com.dust.grpc.kademlia.StoreRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      fileId_ = "";

      data_ = com.google.protobuf.ByteString.EMPTY;

      if (nodeInfoBuilder_ == null) {
        nodeInfo_ = null;
      } else {
        nodeInfo_ = null;
        nodeInfoBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return KademliaServiceProto.internal_static_StoreRequest_descriptor;
    }

    @Override
    public StoreRequest getDefaultInstanceForType() {
      return StoreRequest.getDefaultInstance();
    }

    @Override
    public StoreRequest build() {
      StoreRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StoreRequest buildPartial() {
      StoreRequest result = new StoreRequest(this);
      result.fileId_ = fileId_;
      result.data_ = data_;
      if (nodeInfoBuilder_ == null) {
        result.nodeInfo_ = nodeInfo_;
      } else {
        result.nodeInfo_ = nodeInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StoreRequest) {
        return mergeFrom((StoreRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StoreRequest other) {
      if (other == StoreRequest.getDefaultInstance()) return this;
      if (!other.getFileId().isEmpty()) {
        fileId_ = other.fileId_;
        onChanged();
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.hasNodeInfo()) {
        mergeNodeInfo(other.getNodeInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StoreRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StoreRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object fileId_ = "";
    /**
     * <code>string fileId = 1;</code>
     * @return The fileId.
     */
    public String getFileId() {
      Object ref = fileId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string fileId = 1;</code>
     * @return The bytes for fileId.
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileId = 1;</code>
     * @param value The fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileId() {
      
      fileId_ = getDefaultInstance().getFileId();
      onChanged();
      return this;
    }
    /**
     * <code>string fileId = 1;</code>
     * @param value The bytes for fileId to set.
     * @return This builder for chaining.
     */
    public Builder setFileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private NodeInfo nodeInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        NodeInfo, NodeInfo.Builder, NodeInfoOrBuilder> nodeInfoBuilder_;
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     * @return Whether the nodeInfo field is set.
     */
    public boolean hasNodeInfo() {
      return nodeInfoBuilder_ != null || nodeInfo_ != null;
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     * @return The nodeInfo.
     */
    public NodeInfo getNodeInfo() {
      if (nodeInfoBuilder_ == null) {
        return nodeInfo_ == null ? NodeInfo.getDefaultInstance() : nodeInfo_;
      } else {
        return nodeInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    public Builder setNodeInfo(NodeInfo value) {
      if (nodeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nodeInfo_ = value;
        onChanged();
      } else {
        nodeInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    public Builder setNodeInfo(
        NodeInfo.Builder builderForValue) {
      if (nodeInfoBuilder_ == null) {
        nodeInfo_ = builderForValue.build();
        onChanged();
      } else {
        nodeInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    public Builder mergeNodeInfo(NodeInfo value) {
      if (nodeInfoBuilder_ == null) {
        if (nodeInfo_ != null) {
          nodeInfo_ =
            NodeInfo.newBuilder(nodeInfo_).mergeFrom(value).buildPartial();
        } else {
          nodeInfo_ = value;
        }
        onChanged();
      } else {
        nodeInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    public Builder clearNodeInfo() {
      if (nodeInfoBuilder_ == null) {
        nodeInfo_ = null;
        onChanged();
      } else {
        nodeInfo_ = null;
        nodeInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    public NodeInfo.Builder getNodeInfoBuilder() {
      
      onChanged();
      return getNodeInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    public NodeInfoOrBuilder getNodeInfoOrBuilder() {
      if (nodeInfoBuilder_ != null) {
        return nodeInfoBuilder_.getMessageOrBuilder();
      } else {
        return nodeInfo_ == null ?
            NodeInfo.getDefaultInstance() : nodeInfo_;
      }
    }
    /**
     * <code>.NodeInfo nodeInfo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NodeInfo, NodeInfo.Builder, NodeInfoOrBuilder>
        getNodeInfoFieldBuilder() {
      if (nodeInfoBuilder_ == null) {
        nodeInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NodeInfo, NodeInfo.Builder, NodeInfoOrBuilder>(
                getNodeInfo(),
                getParentForChildren(),
                isClean());
        nodeInfo_ = null;
      }
      return nodeInfoBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StoreRequest)
  }

  // @@protoc_insertion_point(class_scope:StoreRequest)
  private static final StoreRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StoreRequest();
  }

  public static StoreRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StoreRequest>
      PARSER = new com.google.protobuf.AbstractParser<StoreRequest>() {
    @Override
    public StoreRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StoreRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StoreRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StoreRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public StoreRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

